services:
  database:
    image: postgres:16
    command: "postgres -c shared_preload_libraries=pg_stat_statements"
    ports:
      - ${PGPORT-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
